# Generated by Django 4.0.4 on 2022-05-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
