# Generated by Django 4.0.4 on 2022-05-19 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_status_name_alter_task_author_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='app.status', verbose_name='status'),
        ),
        migrations.AddField(
            model_name='label',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task', to='app.task', verbose_name='task'),
        ),
    ]
