# Generated by Django 4.0.4 on 2022-05-19 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_label_status_label_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='status',
        ),
    ]
