# Generated by Django 4.0.4 on 2022-05-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_label_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='label',
            name='task',
        ),
        migrations.RemoveField(
            model_name='label',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', to='app.label', verbose_name='label'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='app.status', verbose_name='status'),
        ),
    ]
